# Generated by Django 4.2.5 on 2024-10-23 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0005_alter_ventas_usuario_delete_usuarios'),
    ]

    operations = [
        migrations.AddField(
            model_name='compras',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='detallecompra',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='detalleventa',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='laboratorios',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='medicamentos',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='proveedores',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='roles',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='ventas',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
