# Generated by Django 4.2.5 on 2024-11-08 21:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0006_compras_activo_detallecompra_activo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleventa',
            name='venta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='ventas.ventas'),
        ),
    ]
