# Generated by Django 4.2.5 on 2024-11-12 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0007_alter_detalleventa_venta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicamentos',
            name='fecha_vencimiento',
        ),
        migrations.CreateModel(
            name='LoteMedicamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('precio_compra', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_compra', models.DateField()),
                ('fecha_vencimiento', models.DateField()),
                ('activo', models.BooleanField(default=True)),
                ('medicamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.medicamentos')),
            ],
        ),
    ]
