# Generated by Django 4.2.5 on 2024-11-14 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0008_remove_medicamentos_fecha_vencimiento_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compras',
            name='cantidad',
        ),
        migrations.RemoveField(
            model_name='compras',
            name='medicamento',
        ),
    ]
