# Generated by Django 4.2.5 on 2024-11-14 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0009_remove_compras_cantidad_remove_compras_medicamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lotemedicamento',
            name='fecha_vencimiento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
