# Generated by Django 4.2.5 on 2024-11-18 03:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0010_alter_lotemedicamento_fecha_vencimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='lotemedicamento',
            name='fecha_produccion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lotemedicamento',
            name='precio_venta',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='lotemedicamento',
            name='cantidad',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='lotemedicamento',
            name='medicamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lotes', to='ventas.medicamentos'),
        ),
    ]
