# Generated by Django 4.2.5 on 2024-11-18 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0011_lotemedicamento_fecha_produccion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedores',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proveedores',
            name='direccion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
