# Generated by Django 4.2.5 on 2024-11-18 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0012_proveedores_descripcion_proveedores_direccion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicamentos',
            name='precio',
        ),
        migrations.AlterField(
            model_name='medicamentos',
            name='stock',
            field=models.IntegerField(default=0),
        ),
    ]
