# Generated by Django 4.2.5 on 2024-11-19 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0014_categorias_tipos_medicamentos_categoria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorias',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tipos',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
