# Generated by Django 4.2 on 2025-05-12 00:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0015_categorias_activo_tipos_activo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('nit_ci', models.CharField(max_length=20)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_factura', models.IntegerField(unique=True)),
                ('fecha_emision', models.DateTimeField(auto_now_add=True)),
                ('nit_empresa', models.CharField(default='123456789', max_length=20)),
                ('codigo_autorizacion', models.CharField(default='7904006306693', max_length=50)),
                ('codigo_control', models.CharField(default='AB-32-DC', max_length=20)),
                ('fecha_limite_emision', models.DateField(blank=True, null=True)),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('activo', models.BooleanField(default=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.cliente')),
                ('venta', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='factura', to='ventas.ventas')),
            ],
        ),
    ]
