# Generated by Django 4.2 on 2025-05-12 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0016_cliente_factura'),
    ]

    operations = [
        migrations.AddField(
            model_name='lotemedicamento',
            name='lote_fabricante',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Lote del Fabricante'),
        ),
    ]
