# Generated by Django 4.2 on 2025-05-26 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0018_verificationcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicamentos',
            name='stock',
        ),
    ]
